name: Markdowns to PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'markdowns/**.md'

jobs:

  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdowns
          output_dir: pdfs
          build_html: false
          
      - uses: actions/upload-artifact@v1
        with:
          name: markdowns
          path: pdfs
