name: Markdowns to PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'markdowns/**'

jobs:

  convert:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdowns
          output_dir: pdfs
          build_html: false
          theme: md-pdf-theme.css
          
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Convert markdowns to pdfs"
